{% set version = "0.20.1" %}
{% set sha256 = "8c58f14adaa3b947daf26c19bc1e98c4e0702cdc31cf99153e6f06904d492bf8" %}

package:
  name: python-graphviz
  version: {{ version }}

source:
  fn: python-graphviz-{{ version }}.zip
  url: https://pypi.io/packages/source/g/graphviz/graphviz-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 0
  script:
    - python -m pip install --no-deps --ignore-installed "${SRC_DIR}"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - graphviz <=3.0.0

test:
  imports:
    - graphviz
  requires:
    - dask

about:
  home: https://github.com/xflr6/graphviz
  doc_url: https://graphviz.readthedocs.io
  dev_url: https://github.com/xflr6/graphviz

  license: MIT
  license_family: MIT
  license_file: LICENSE.txt

  summary: Simple Python interface for Graphviz
  description: |
    This package facilitates the creation and rendering of graph
    descriptions in the DOT language of the Graphviz graph
    drawing software from Python.

extra:
  recipe-maintainers:
    - jakirkham
    - scopatz
