{% set version = "0.20.3" %}

package:
  name: python-graphviz
  version: {{ version }}

source:
  fn: python-graphviz-{{ version }}.zip
  url: https://pypi.io/packages/source/g/graphviz/graphviz-{{ version }}.zip
  sha256: 09d6bc81e6a9fa392e7ba52135a9d49f1ed62526f96499325930e87ca1b5925d

build:
  skip: true  # [py<38 or unix]
  number: 0
  script:
    - python -m pip install --no-deps --no-build-isolation --ignore-installed "{{SRC_DIR}}"
    - set "GRAPHVIZ_EXECUTABLE=%%PREFIX%%/Library/bin/dot.exe"  # [win]
    - set "PATH=%%PREFIX%%/Library/bin;%%PATH%%"  # [win]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - graphviz
    - gts  # [win]  # Add GTS dependency for Windows

test:
  source_files:
    - tests
  imports:
    - graphviz
  commands:
    - pip check
    - |
      if exist "%%PREFIX%%/Library/bin/dot.exe" (
        echo "Graphviz found at %%PREFIX%%/Library/bin/dot.exe"
      ) else (
        echo "Graphviz not found!"
      )  # [win]
    - "%%PREFIX%%/Library/bin/dot.exe" -V  # [win]
    - dir "%%PREFIX%%/Library/bin/*.exe"  # [win]  # List all executables to verify
    - pytest tests -v  # [unix]
    - |
      pytest tests -v -k "not test_pipe and not test_render and not test_render_img and not test_render_outfile_differnt_parent and not test_render_raises_before_save and not test_subgraph_render and not test_subgraph and not test_visualize"  # [win]
  requires:
    - pip
    - pytest
    - pytest-mock >=3
    - pytest-cov
    - coverage
    - graphviz  # Add graphviz to test requirements
    - gts  # [win]  # Add GTS dependency for Windows tests

about:
  home: https://github.com/xflr6/graphviz
  doc_url: https://graphviz.readthedocs.io
  dev_url: https://github.com/xflr6/graphviz

  license: MIT
  license_family: MIT
  license_file: LICENSE.txt

  summary: Simple Python interface for Graphviz
  description: |
    This package facilitates the creation and rendering of graph
    descriptions in the DOT language of the Graphviz graph
    drawing software from Python.

extra:
  recipe-maintainers:
    - jakirkham
    - scopatz
