{% set version = "0.7.1" %}
{% set sha256 = "c7744df945fa90791ad9b4183a6a7dc8220d63a7b8a5f8f93ba62086f1e69e83" %}
{% set number = "0" %}

package:
  name: python-graphviz
  version: {{ version }}

source:
  fn: graphviz-{{ version }}.zip
  url: https://files.pythonhosted.org/packages/source/g/graphviz/graphviz-{{ version }}.zip
  sha256: {{ sha256 }}
  patches:
    # needed due to the Windows batch script wrappers in conda-forge Graphviz
    # see https://github.com/conda-forge/graphviz-feedstock/blob/bbfe3c7be2a448dd11db165a18c3edfd5ee6a95d/recipe/bld.bat#L27-L32
    - windows-bat.patch  # [win]

build:
  number: {{ number }}
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - graphviz

test:
  imports:
    - graphviz
  requires:
    - dask

about:
  home: https://github.com/xflr6/graphviz
  doc_url: https://graphviz.readthedocs.io
  dev_url: https://github.com/xflr6/graphviz

  license: MIT
  license_family: MIT
  license_file: LICENSE

  summary: Simple Python interface for Graphviz
  description: |
    This package facilitates the creation and rendering of graph
    descriptions in the DOT language of the Graphviz graph
    drawing software from Python.

extra:
  recipe-maintainers:
    - jakirkham
