travis:
  secure:
    BINSTAR_TOKEN: gibYTxnR8GM6fvm3cKKAcKkR0/fwVZK2/ZK0ywRy79QO7hkOzEZMJeEo8yg/8entapMsOiWMHGsSNfYciaxADMElMy/Mbj/iS6yJXFilx3Qz1nzLlFqF336/l4SzdDNNwFNXnSatlif65K8qnaPsz19XQdGmOeKJ85fAgmqCJhI8okit565+pfn235bPNunEpO1Qk5agK3V3nY14AZm5JZbPxEqjh8jLaIBLHlU4e9viNiqjzIsCmSKDMzRWCh6QTGkXkRz0oSknRwPOfQT9++9SuXUQFhsyyw+9eA/ILyMuvqN5ETDmch5Rmd1cIFuzCRqiv0E/NO+FjeAny0qtvNbYPkY8wFpj7hJWAMlQZ+odfUR8BNTma9U//Q4SekOC/ugSArpGcfzd5E5O/wTlEaff4Vmcw2RPR9EhuaAP7JMEQVrwAET3VPSQGWkTcKuSbebg92yQDtBptj2qIt/A3qCqBESuHDVimn3Y41ETNdA50c1Gmy8IIm3or3UW6jaPGSuQPaOBGgzTpx5GPISIje2IIYkfAJPT1dewfMaUj5NJ7c5CN1/BzNHWSD9H3WNdFEhYNnj0GnkSPwrYSVw44pbggQUhc/Y4/4Fo+vEezhDfTvZCHloUrOYe52dwbZhInZCB4AKZsZNNhXXhGNRWnT2UMPwQYe7AsmG3dCwDNqU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
