appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: WzCahEtkzGri2H4Uk/OOiMMZj5ktd1hr4tgCNRFrH6/D6eGS8DtbZbY/RqmcAFMUGIXxU8QQGRyRlV2YbMGo58nmI/U6JgWf3h6tAz5y5UmC6nv5TYguxh85W9NrH7LCM5a+Nmpha5KgoyVvCS/7JOKlVxKSoPkJiTHI6hIQo3Bwp7Ro7NgKZNzI+q9l8jNAba+bLutW/WFPLVYBMY9b+FLzA0pIRk5yHSMQEX/WFPpVnfSB+q7MuLoJBOXd6TYJQ7CfmzZJAURnJdWLTI2w7bAiGdYsPG9qJneOZj46BlFw8thCtPyg1EaD9gmSTtrnboSmyMA3vCt2/6LENofVzShcZ6xFbNV7xg3srmYkOZp7UebX0vaPXTOyTtgb6Ci1nNqWr4pVPbfda5x3Jv0D8ou5WVK+jTViacRL/s8rwR51bsWkeO6nzsKzmOypgYVRHHvncym+gq8wdV/MO8vAvS6GSUsvKi7Tz+EyqqBsr57fULTh33+2U0eiYuedclaryi1K4bzBeAASHI42E+X8orw9UCcKiW65FGZOK2KZ4YMMNOxNqn/jOm0iIC21jojPra7Zd9XUXLEKzXxIpvnLVVcqRUD18Bj8E6tbWLmcidsmyrx0TrWjdNcW0/Ghqz5GX1pXDjedI5ZjLCvQZEaROkv5dal2XxikAC8zZ3iIbLM=}
